Github Action to adjust version information in antora.yml depending on current branch or version tag.

image:{github-actions-url}/{job-generate-docs}/{badge}[Github Badge, link={github-actions-url}/{job-generate-docs}]
image:{github-actions-url}/{job-ci}/{badge}[Github Badge, link={github-actions-url}/{job-ci}]

* Github Repository -> {url-project}
* Documentation -> https://docs.cloud.sommerfeld.io/{project-name}-docs/main
* Where to file issues -> {url-project}/issues

== Inputs
[cols="1,1,1,3", options="header"]
|===
|Input |Type |Required |Description
|git_ref |String |true |Githib Ref `${{github.ref}}`
|===

== Outputs
An updated `docs/antora.yml` file.

== Example usage
The scripts expects Antora docs inside a `docs` folder and expects a `docs/antora.yml` file.


[source, yaml]
----
- name: Adjust version in antora.yml
  uses: sebastian-sommerfeld-io/github-action-update-antora-yml@main
  with:
    ref: ${{github.ref}}
----

== Risks and Technical Debts
Scale for Probability and Impact: Low, Medium and High

[cols="^1,2,5a,1,1,5a", options="header"]
|===
|# |Title |Description |Probability |Impact |Response
|{counter:usage} |- |- |- |- |-
|===

== Contact
Feel free to contact me via sebastian@sommerfeld.io or visit my website https://www.sommerfeld.io.
