Github Action to adjust version information in antora.yml depending on current branch or version tag.

image:{github-actions-url}/{job-generate-docs}/{badge}[Github Badge, link={github-actions-url}/{job-generate-docs}]
image:{github-actions-url}/{job-ci}/{badge}[Github Badge, link={github-actions-url}/{job-ci}]

== About this action

* Github Repository -> {url-project}
* Where to file issues -> {url-project}/issues

== Inputs
[cols="1,1,1,3", options="header"]
|===
|Input |Type |Required |Description
|git_ref |String |true |Githib Ref `${{github.ref}}`
|file |String |false |Path to antora.yml (default = `docs/antora.yml`)
|===

== Outputs
An updated `docs/antora.yml` file.

== Example usage
The scripts expects Antora docs inside a `docs` folder and expects a `docs/antora.yml` file.

[source, yaml]
----
- name: Adjust version in antora.yml
  uses: sebastian-sommerfeld-io/github-action-update-antora-yml@main
  with:
    ref: ${{github.ref}}
----

== Local development
To test the behavior of this action, you can run the following command from the src/main folder:

* `./entrypoint.sh refs/heads/main ../../docs/antora.yml` to set `main` as version
* `./entrypoint.sh v0.1.5-SNAPSHOT ../../docs/antora.yml` to set `v0.1.5-SNAPSHOT` as version

This command executes the same script that is triggered from the GitHub Action workflow associated with the project. By running it locally, you can observe the behavior and ensure that the action performs as expected. It allows you to validate the functionality and behavior of the script without relying solely on the automated workflow execution.

Please be aware that running the aforementioned command may modify your `antora.yml` file. Therefore, be prepared to revert any changes made by the script if necessary before committing your changes.

== Risks and Technical Debts
Scale for Probability and Impact: Low, Medium and High

[cols="^1,2,5a,1,1,5a", options="header"]
|===
|# |Title |Description |Probability |Impact |Response
|{counter:usage} |- |- |- |- |-
|===

== Contact
Feel free to contact me via sebastian@sommerfeld.io or visit my website https://www.sommerfeld.io.
